name: hr-functionapps

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select env:- dev/qa/prod'
        required: true
        options:
        - dev
        - qa
        - prod  
      functionApp:
        type: choice
        description: 'Select function app to deploy'
        required: true
        options:
        - hr-functionappcore
        - hr-associatesync-func  
