name: testingfunctionapps

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select env:- dev/qa/prod'
        required: true
        options:
        - dev
        - qa
        - prod  
      Application:
        type: choice
        description: 'Select function app to deploy'
        required: true
        options:
        - App-1
        - App-2 

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV: '${{ github.event.inputs.environment }}'  
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    - name: greet
      run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}-${{ env.ENV }}.parameters.json "        
          echo "Function app is ${{ github.event.inputs.functionApp }} / ${{ inputs.functionApp }}-${{ env.ENV }}.parameters.json "     
          echo " ${{ github.run_id }}"
          echo " ${{ github.run_number }}"
